apiVersion: v1
kind: Service
metadata:
  name: kepler-frontend
spec:
  selector:
    app: kepler-frontend
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30050
  type: NodePort